spring.application.name=Spring-Boot-MVC-and-RESTful-APIs
server.port=9090
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=saurabh
spring.datasource.password=Pass@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console